---
# build.yaml
#
# CI/CD scripts configuration file
#
# author  : stefan schablowski
# contact : stefan.schablowski@desmodyne.com
# created : 2018-10-07


# container namespace used locally when building image
local_namespace: desmodyne

# path from this file to project root
path_to_proj_root: ../..


# list of data sets to configure container images
images:

  # name of the container image
  ci-vault-client:

    # path to container image configuration, relative to project root
    image_conf_path: code/docker/ci-vault-client/Dockerfile
    # container image tag
    image_tag: latest

  ci-vault-server:
    image_conf_path: code/docker/ci-vault-server/Dockerfile
    image_tag: latest
