---
# .gitlab-ci.yml
#
# gitlab CI/CD YAML configuration file
#
# author  : stefan schablowski
# contact : stefan.schablowski@desmodyne.com
# created : 2018-09-30


# https://gitlab.com/help/ci/quick_start/README#creating-a-gitlab-ciyml-file
# gitlab docs for this file: https://gitlab.com/help/ci/yaml/README.md
# gitlab docs on using docker-in-docker executor:
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html ...
#  ... #use-docker-in-docker-executor
# https://gitlab.com/help/ci/docker/using_docker_images.md ...
#  ... #define-image-and-services-from-gitlab-ciyml

stages:
  - upload

upload:
  only:
    - master
  script: cicd/bin/upload
  stage:  upload
